const card1 = [
  {
    availability: 1,
    imagenHouse: "./houses/house1.jpg",
    redStar: "./houses/redStar.png",
    span1: "5.0",
    span2: "(6)",
    span3: "USA",
    title1: "Denver Paradaise",
    price: "From $ 1,999",
    id: 1,
  },
  {
    availability: 0,
    imagenHouse: "./houses/house2.jpg",
    redStar: "./houses/redStar.png",
    span1: "6.0",
    span2: "(2)",
    span3: "MEX",
    title1: "House ",
    price: "From $ 1,360",
    id: 2,
  },
  {
    availability: 0,
    imagenHouse: "./houses/house3.jpg",
    redStar: "./houses/redStar.png",
    span1: "10.0",
    span2: "(6)",
    span3: "BRZ",
    title1: "Big House ",
    price: "From $ 1,236",
    id: 3,
  },
  {
    availability: 1,
    imagenHouse: "./houses/house4.jpg",
    redStar: "./houses/redStar.png",
    span1: "7.0",
    span2: "(3)",
    span3: "MEX",
    title1: "House ",
    price: "From $ 999",
    id: 4,
  },
  {
    availability: 1,
    imagenHouse: "./houses/house5.jpg",
    redStar: "./houses/redStar.png",
    span1: "8.0",
    span2: "(5)",
    span3: "MEX",
    title1: "House ",
    price: "From $ 999",
    id: 5,
  },
];

export default card1;
